name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '8'
    - name: Build with Maven
      run: mvn package
    - name: tomcat deployment
      run:  curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} -T /home/ec2-user/actions-runner/_work/spring-petclinic/spring-petclinic/target/petclinic.war 'http://ec2-13-233-172-202.ap-south-1.compute.amazonaws.com:8081/manager/text/deploy?path=/runnertomcat&update=true'

