name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '8'
    - name: Build with Maven
      run: mvn package
